### ISSUE TITLE
Refactor build process

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/hm-config#154]
Problems to address:

- [PyGObject](https://pypi.org/project/PyGObject/) is not heavily [used](https://github.com/NebraLtd/hm-config/blob/8cc544fb02371a76ba49eba548c8d90ec804bf2f/lib/cputemp/service.py#L30) but introduces a dependency that is a PITA. It takes forever to build with `pip` and we have not been able to get it working using the [system](https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian) installs.
- Removing venv. This was prevented previously because PyGObject would complain after venv removed:

```
Traceback (most recent call last):
  File "/opt/lib/cputemp/service.py", line 30, in <module>
    from gi.repository import GObject
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```

- Unpinning package versions. This was last attempted at the same time as other changes and likely contributed to the issues.

**Comment by shawaj** [comment]
Related to #127
