### ISSUE TITLE
No such file or directory: '/opt/venv/lib/python3.7/site-packages/hm_pyhelper/gateway_mfr'

### ISSUE THREAD

**Issue by ashwinvandijk** [NebraLtd/hm-config#213]
Added the latest version to my docker-compose, but it throws this error after pairing with the app. I inspected the container using `dive` and the `gateway_mfr` folder indeed isn't there.

```
[DEBUG] - gatewayconfig.gatewayconfig_app - (gatewayconfig_app.py).__init__ -- /opt/gatewayconfig/gatewayconfig_app.py:(40) - Read eth0 mac address XX:XX:XX:XX:XX:XX and wlan0 XX:XX:XX:XX:XX:XX

[ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/venv/lib/python3.7/site-packages/hm_pyhelper/miner_param.py:(87) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/venv/lib/python3.7/site-packages/hm_pyhelper/gateway_mfr': '/opt/venv/lib/python3.7/site-packages/hm_pyhelper/gateway_mfr'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/hm_pyhelper/miner_param.py", line 83, in get_gateway_mfr_version
    check=True
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/venv/lib/python3.7/site-packages/sentry_sdk/integrations/stdlib.py", line 193, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)  # type: ignore
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/venv/lib/python3.7/site-packages/hm_pyhelper/gateway_mfr': '/opt/venv/lib/python3.7/site-packages/hm_pyhelper/gateway_mfr'
2022-11-29 10:04:17,798 - [ERROR] - gatewayconfig.gatewayconfig_shared_state - (gatewayconfig_shared_state.py).load_public_key -- /opt/gatewayconfig/gatewayconfig_shared_state.py:(42) - Unable to read public key.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/hm_pyhelper/miner_param.py", line 83, in get_gateway_mfr_version
    check=True
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/venv/lib/python3.7/site-packages/sentry_sdk/integrations/stdlib.py", line 193, in sentry_patched_popen_init
    rv = old_popen_init(self, *a, **kw)  # type: ignore
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/venv/lib/python3.7/site-packages/hm_pyhelper/gateway_mfr': '/opt/venv/lib/python3.7/site-packages/hm_pyhelper/gateway_mfr'
```

**Comment by shawaj** [comment]
@NebraLtd/developers could you take a look and see if we can reproduce this?
