### ISSUE TITLE
Can't find org.bluez with new setup - possibly because running in venv

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-config#93]
```
root@nebra-d06a21:/opt# ./start-gateway-config.sh 
^C
2021-09-14 02:53:03;DEBUG;Starting with the following ENV:
        SENTRY_DSN=https://3234e2c67fe04c3e9f8b0c9b118c415a@o571444.ingest.sentry.io/5725518
        BALENA_APP_NAME=HELIUM-LIGHT-TEST
        BALENA_DEVICE_UUID=28c44310bfc8ffc6098bce2b3696336e
        VARIANT=NEBHNT-IN1
        ETH0_MAC_ADDRESS_FILEPATH=/sys/class/net/eth0/address
        WLAN0_MAC_ADDRESS_FILEPATH=/sys/class/net/wlan0/address
        MINER_KEYS_FILEPATH=/var/data/public_keys
        DIAGNOSTICS_JSON_URL=http://localhost:80?json=true
        ETHERNET_IS_ONLINE_FILEPATH=/sys/class/net/eth0/carrier
        FIRMWARE_VERSION=2021.09.09.0

2021-09-14 02:53:03;DEBUG;Read eth0 mac address DC:A6:32:D1:47:D6 and wlan0 42:47:6A:28:96:10
2021-09-14 02:53:03;DEBUG;Read onboarding pub_key: 11xcYBAeqhYfRznipZRvqaRF8H9jwVnTVftPDsAfLL7gJDK2hD9 + animal_name: suave-heather-hare
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 363, in get_name_owner
    's', (bus_name,), **keywords)
  File "/opt/venv/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.bluez': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "gatewayconfig/__main__.py", line 49, in <module>
    main()
  File "gatewayconfig/__main__.py", line 20, in main
    start()
  File "gatewayconfig/__main__.py", line 40, in start
    ETH0_MAC_ADDRESS_FILEPATH, WLAN0_MAC_ADDRESS_FILEPATH, MINER_KEYS_FILEPATH, DIAGNOSTICS_JSON_URL, ETHERNET_IS_ONLINE_FILEPATH, FIRMWARE_VERSION)
  File "/opt/gatewayconfig/gatewayconfig_app.py", line 42, in __init__
    self.bluetooth_services_processor = BluetoothServicesProcessor(eth0_mac_address, wlan0_mac_address, onboarding_key, pub_key, firmware_version, ethernet_is_online_filepath, self.shared_state)
  File "/opt/gatewayconfig/processors/bluetooth_services_processor.py", line 11, in __init__
    self.register()
  File "/opt/lib/cputemp/service.py", line 94, in register
    adapter = BleTools.find_adapter(self.bus)
  File "/opt/lib/cputemp/bletools.py", line 44, in find_adapter
    "/"),
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/opt/venv/lib/python3.7/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/opt/venv/lib/python3.7/site-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/opt/venv/lib/python3.7/site-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez was not provided by any .service files
Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by vpetersson** [comment]
@shawaj how and where did you get this?

**Comment by shawaj** [comment]
don't worry - this is with my dbus container testing @vpetersson
